#!/usr/bin/env bun
import { readdirSync, readFileSync, writeFileSync, existsSync } from 'fs';
import { join } from 'path';

const LOCALES_DIR = 'src/internationalization/locales';
const OUTPUT = 'src/internationalization/locales.generated.ts';

const codes = readdirSync(LOCALES_DIR, { withFileTypes: true })
  .filter((e) => e.isDirectory() && existsSync(join(LOCALES_DIR, e.name, 'translation.json')))
  .map((e) => e.name)
  .sort();

if (codes.length === 0) {
  console.error(`No locales found in ${LOCALES_DIR}`);
  process.exit(1);
}

const toIdent = (code: string): string => code.replace(/-/g, '_');
const toKey = (code: string): string => (code.includes('-') ? `'${code}'` : code);

const lines = [
  '// AUTO-GENERATED by scripts/generate-locales.ts — DO NOT EDIT.',
  '// Regenerate with: bun run locales:generate',
  "import type { Translation } from './types';",
  ...codes.map((c) => `import ${toIdent(c)} from './locales/${c}/translation.json';`),
  '',
  `export type SupportedLanguage = ${codes.map((c) => `'${c}'`).join(' | ')};`,
  '',
  'export const translations: Record<SupportedLanguage, Translation> = {',
  ...codes.map((c, i) => `  ${toKey(c)}: ${toIdent(c)} as Translation${i < codes.length - 1 ? ',' : ''}`),
  '};',
  ''
];

const content = lines.join('\n');

if (process.argv.includes('--check')) {
  const current = existsSync(OUTPUT) ? readFileSync(OUTPUT, 'utf-8') : '';
  if (current !== content) {
    console.error(`${OUTPUT} is out of date. Run: bun run locales:generate`);
    process.exit(1);
  }
  console.log(`✅ ${OUTPUT} is up to date (${codes.length} locales)`);
} else {
  writeFileSync(OUTPUT, content);
  console.log(`✅ Generated ${OUTPUT}: ${codes.join(', ')}`);
}
